- name: Install Apache2
  ansible.builtin.apt:
    name: apache2
    update_cache: yes
    state: latest
- name: Enable Mod Rewrite
  apache2_module:
    name: rewrite
    state: present
    notify:
      - restart apache2