---
- name: Install Nginx
  hosts: main
  remote_user: ubuntu
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    acme_challenge_type: http-01
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    # acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
    acme_version: 2
    acme_email: justintlaw97@gmail.com
    letsencrypt_dir: /etc/letsencrypt
    letsencrypt_keys_dir: /etc/letsencrypt/keys
    letsencrypt_csrs_dir: /etc/letsencrypt/csrs
    letsencrypt_certs_dir: /etc/letsencrypt/certs
    letsencrypt_account_dir: /etc/letsencrypt/account
    letsencrypt_account_key: /etc/letsencrypt/account/account.key
    domain_name: jenkins.justincodes.dev

  tasks:
    - name: Create Required Directories
      file:
        path: "/etc/letsencrypt/{{ item }}"
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rwx,o=x
      with_items:
      - account
      - certs
      - csrs
      - keys
    - name: Generate Let's Encrypt Account Key
      command: openssl genrsa 4096 | sudo tee {{ letsencrypt_account_key }}
      args:
        chdir: "{{ letsencrypt_account_dir }}"
        creates: "{{ letsencrypt_account_key }}"
    - name: Generate The Private Key
      openssl_privatekey:
        path: /etc/letsencrypt/keys/jenkins.justincodes.dev.key
    - name: Generate an OpenSSL Certificate Signing Request with Subject information
      openssl_csr:
        path: "{{ letsencrypt_csrs_dir }}/jenkins.justincodes.dev.csr"
        privatekey_path: /etc/letsencrypt/keys/jenkins.justincodes.dev.key
        country_name: US
        email_address: justintlaw97@gmail.com
        common_name: "{{ domain_name }}"
    - name: Begin Let's Encrypt challenges
      acme_certificate:
        acme_directory: "{{ acme_directory }}"
        acme_version: "{{ acme_version }}"
        account_key_src: "{{ letsencrypt_account_key }}"
        account_email: "{{ acme_email }}"
        terms_agreed: 1
        challenge: "{{ acme_challenge_type }}"
        csr: "{{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"
        dest: "{{ letsencrypt_certs_dir }}/{{ domain_name }}.crt"
        fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}.crt"
        remaining_days: 91
      register: acme_challenge_justincodes
    - name: Create .well-known/acme-challenge directory
      file:
        path: /var/run/jenkins/war/.well-known/acme-challenge
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
    - name: DEBUG
      debug:
        msg: "{{ acme_challenge_justincodes }}"
    - name: Implement http-01 challenge files
      copy:
        content: "{{ acme_challenge_justincodes['challenge_data'][item]['http-01']['resource_value'] }}"
        dest: "/var/run/jenkins/war/{{ acme_challenge_justincodes['challenge_data'][item]['http-01']['resource'] }}"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      with_items:
      - "{{ domain_name }}"
    - name: Complete Let's Encrypt challenges
      acme_certificate:
        acme_directory: "{{ acme_directory }}"
        acme_version: "{{ acme_version }}"
        account_key_src: "{{ letsencrypt_account_key }}"
        account_email: "{{ acme_email }}"
        challenge: "{{ acme_challenge_type }}"
        csr: "{{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"
        dest: "{{ letsencrypt_certs_dir }}/{{ domain_name }}.crt"
        chain_dest: "{{ letsencrypt_certs_dir }}/chain_{{ domain_name }}.crt"
        fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ domain_name }}.crt"
        data: "{{ acme_challenge_justincodes }}"
    - name: Give Nginx Access To Cert Directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: www-data
        mode: u=rwx,g=rx,o=rx
      with_items:
        - "/etc/letsencrypt"
        - "/etc/letsencrypt/certs"
        - "/etc/letsencrypt/keys"
    - name: Give Nginx Access To Cert Files
      file:
        path: "{{ item }}"
        state: file
        owner: root
        group: www-data
        mode: u=rw,g=r,o=r
      with_items:
        - "/etc/letsencrypt/keys/jenkins.justincodes.dev.key"
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted